services:
  db:
    image: postgres
    container_name: crm-database
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"

  # backend:
  #   container_name: crm-backend
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .backend:./* 


  # frontend:
  #   container_name: crm-frontend
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports: 
  #     - "3000:3000"
  #   volumes:
  #     - .client:/app
  #     - /app/node_modules



  pgadmin:
    image: dpage/pgadmin4
    container_name: crm-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "54321:80"
    depends_on:
      - db
